import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import ClientProviders from "~/components/ClientProviders";
import ServerProviders from "~/components/ServerProviders";
// import TailwindConfig from "~/payload/globals/SiteConfig";

export const metadata: Metadata = {
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
	title: "UIFoundry",
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	auth,
	children,
}: Readonly<{ auth: React.ReactNode; children: React.ReactNode }>) {
	return (
		<html
			className={`${geist.variable}`}
			lang="en"
			// next-themes error suppression
			suppressHydrationWarning
			title="UIFoundry"
		>
			<body>
				<ServerProviders>
					{/* <TailwindConfig /> */}
					<ClientProviders>
						{children}
						{auth}
					</ClientProviders>
				</ServerProviders>
			</body>
		</html>
	);
}
