import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import ServerProviders from "./providers.server";
import ClientProviders from "./providers.client";
import TailwindConfig from "~/payload/globals/TailwindConfig";

export const metadata: Metadata = {
	title: "UIFoundry",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable}`}>
			<body>
				<ServerProviders>
					<TailwindConfig />
					<ClientProviders>
						{children}
					</ClientProviders>
				</ServerProviders>
			</body>
		</html>
	);
}
