export const socialIcons = {
  Arc: {
    id: 95,
    category: "Social",
    route: {
      dark: "https://svgl.app/library/arc_dark.svg",
      light: "https://svgl.app/library/arc.svg",
    },
    title: "Arc",
    url: "https://arc.dev",
  },
  Bluesky: {
    id: 450,
    category: "Social",
    route: "https://svgl.app/library/bluesky.svg",
    title: "Bluesky",
    url: "https://blueskyweb.xyz/",
  },
  Carrd: {
    id: 446,
    category: ["Social"],
    route: "https://svgl.app/library/carrd.svg",
    title: "Carrd",
    url: "https://carrd.co/",
  },
  "daily.dev": {
    id: 452,
    category: ["Social", "Community"],
    route: {
      dark: "https://svgl.app/library/daily-dev-dark.svg",
      light: "https://svgl.app/library/daily-dev-ligth.svg",
    },
    title: "daily.dev",
    url: "https://daily.dev/",
  },
  Facebook: {
    id: 48,
    brandUrl: "https://about.meta.com/brand/resources/facebook/logo/",
    category: "Social",
    route: "https://svgl.app/library/facebook.svg",
    title: "Facebook",
    url: "https://www.facebook.com/",
  },
  Hashnode: {
    id: 283,
    category: "Social",
    route: "https://svgl.app/library/hashnode.svg",
    title: "Hashnode",
    url: "https://hashnode.com",
  },
  Infojobs: {
    id: 218,
    category: "Social",
    route: "https://svgl.app/library/infojobs-logo.svg",
    title: "Infojobs",
    url: "https://www.infojobs.net/",
  },
  Instagram: {
    id: 232,
    brandUrl: "https://about.instagram.com/brand",
    category: "Social",
    route: {
      dark: "https://svgl.app/library/instagram_dark.svg",
      light: "https://svgl.app/library/instagram.svg",
    },
    title: "Instagram",
    url: "https://www.instagram.com/",
  },
  LinkedIn: {
    id: 70,
    brandUrl: "https://brand.linkedin.com/",
    category: "Social",
    route: "https://svgl.app/library/linkedin.svg",
    title: "LinkedIn",
    url: "https://www.linkedin.com/",
  },
  Mastodon: {
    id: 185,
    category: "Social",
    route: "https://svgl.app/library/mastodon.svg",
    title: "Mastodon",
    url: "https://joinmastodon.org/",
  },
  Matrix: {
    id: 72,
    category: "Social",
    route: {
      dark: "https://svgl.app/library/matrix-dark.svg",
      light: "https://svgl.app/library/matrix-light.svg",
    },
    title: "Matrix",
    url: "https://matrix.org/",
  },
  Messenger: {
    id: 199,
    category: "Social",
    route: "https://svgl.app/library/messenger.svg",
    title: "Messenger",
    url: "https://www.messenger.com/",
  },
  Meta: {
    id: 376,
    brandUrl: "https://about.meta.com/brand/resources/",
    category: "Social",
    route: "https://svgl.app/library/meta.svg",
    title: "Meta",
    url: "https://about.meta.com/es/",
  },
  Patreon: {
    id: 288,
    category: "Social",
    route: {
      dark: "https://svgl.app/library/patreon_dark.svg",
      light: "https://svgl.app/library/patreon.svg",
    },
    title: "Patreon",
    url: "https://www.patreon.com/",
  },
  Peerlist: {
    id: 289,
    category: "Social",
    route: "https://svgl.app/library/peerlist.svg",
    title: "Peerlist",
    url: "https://www.peerlist.io/",
  },
  Pinterest: {
    id: 314,
    category: "Social",
    route: "https://svgl.app/library/pinterest.svg",
    title: "Pinterest",
    url: "https://pinterest.com/",
  },
  Reddit: {
    id: 325,
    brandUrl: "https://redditinc.com/brand",
    category: "Social",
    route: "https://svgl.app/library/reddit.svg",
    title: "Reddit",
    url: "https://www.reddit.com/",
  },
  Skype: {
    id: 222,
    category: "Social",
    route: "https://svgl.app/library/skype.svg",
    title: "Skype",
    url: "https://www.skype.com/",
  },
  Telegram: {
    id: 71,
    category: "Social",
    route: "https://svgl.app/library/telegram.svg",
    title: "Telegram",
    url: "https://web.telegram.org/",
  },
  Threads: {
    id: 231,
    category: "Social",
    route: {
      dark: "https://svgl.app/library/threads_dark.svg",
      light: "https://svgl.app/library/threads.svg",
    },
    title: "Threads",
    url: "https://threads.net/",
  },
  TikTok: {
    id: 398,
    category: "Social",
    route: "https://svgl.app/library/tiktok.svg",
    title: "TikTok",
    url: "https://www.tiktok.com/",
  },
  Twitter: {
    id: 49,
    category: "Social",
    route: "https://svgl.app/library/twitter.svg",
    title: "Twitter",
    url: "https://twitter.com/",
  },
  VK: {
    id: 263,
    category: "Social",
    route: "https://svgl.app/library/vk.svg",
    title: "VK",
    url: "https://vk.com",
  },
  WhatsApp: {
    id: 73,
    category: "Social",
    route: "https://svgl.app/library/whatsapp.svg",
    title: "WhatsApp",
    url: "https://web.whatsapp.com/",
  },
  "X (formerly Twitter)": {
    id: 254,
    brandUrl: "https://about.x.com/en/who-we-are/brand-toolkit",
    category: "Social",
    route: {
      dark: "https://svgl.app/library/x_dark.svg",
      light: "https://svgl.app/library/x.svg",
    },
    title: "X (formerly Twitter)",
    url: "https://x.com",
  },
  YouTube: {
    id: 64,
    category: ["Google", "Social"],
    route: "https://svgl.app/library/youtube.svg",
    title: "YouTube",
    url: "https://www.youtube.com/",
    wordmark: "https://svgl.app/library/youtube-wordmark.svg",
  },
};

export type SocialIconKey = keyof typeof socialIcons;
