/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconField".
 */
export type IconField =
  | (
      | "AArrowDown"
      | "AArrowUp"
      | "ALargeSmall"
      | "Accessibility"
      | "Activity"
      | "AirVent"
      | "Airplay"
      | "AlarmClock"
      | "AlarmClockCheck"
      | "AlarmClockMinus"
      | "AlarmClockOff"
      | "AlarmClockPlus"
      | "AlarmSmoke"
      | "Album"
      | "AlignCenter"
      | "AlignCenterHorizontal"
      | "AlignCenterVertical"
      | "AlignEndHorizontal"
      | "AlignEndVertical"
      | "AlignHorizontalDistributeCenter"
      | "AlignHorizontalDistributeEnd"
      | "AlignHorizontalDistributeStart"
      | "AlignHorizontalJustifyCenter"
      | "AlignHorizontalJustifyEnd"
      | "AlignHorizontalJustifyStart"
      | "AlignHorizontalSpaceAround"
      | "AlignHorizontalSpaceBetween"
      | "AlignJustify"
      | "AlignLeft"
      | "AlignRight"
      | "AlignStartHorizontal"
      | "AlignStartVertical"
      | "AlignVerticalDistributeCenter"
      | "AlignVerticalDistributeEnd"
      | "AlignVerticalDistributeStart"
      | "AlignVerticalJustifyCenter"
      | "AlignVerticalJustifyEnd"
      | "AlignVerticalJustifyStart"
      | "AlignVerticalSpaceAround"
      | "AlignVerticalSpaceBetween"
      | "Ambulance"
      | "Ampersand"
      | "Ampersands"
      | "Amphora"
      | "Anchor"
      | "Angry"
      | "Annoyed"
      | "Antenna"
      | "Anvil"
      | "Aperture"
      | "AppWindow"
      | "AppWindowMac"
      | "Apple"
      | "Archive"
      | "ArchiveRestore"
      | "ArchiveX"
      | "Armchair"
      | "ArrowBigDown"
      | "ArrowBigDownDash"
      | "ArrowBigLeft"
      | "ArrowBigLeftDash"
      | "ArrowBigRight"
      | "ArrowBigRightDash"
      | "ArrowBigUp"
      | "ArrowBigUpDash"
      | "ArrowDown"
      | "ArrowDown01"
      | "ArrowDown10"
      | "ArrowDownAZ"
      | "ArrowDownFromLine"
      | "ArrowDownLeft"
      | "ArrowDownNarrowWide"
      | "ArrowDownRight"
      | "ArrowDownToDot"
      | "ArrowDownToLine"
      | "ArrowDownUp"
      | "ArrowDownWideNarrow"
      | "ArrowDownZA"
      | "ArrowLeft"
      | "ArrowLeftFromLine"
      | "ArrowLeftRight"
      | "ArrowLeftToLine"
      | "ArrowRight"
      | "ArrowRightFromLine"
      | "ArrowRightLeft"
      | "ArrowRightToLine"
      | "ArrowUp"
      | "ArrowUp01"
      | "ArrowUp10"
      | "ArrowUpAZ"
      | "ArrowUpDown"
      | "ArrowUpFromDot"
      | "ArrowUpFromLine"
      | "ArrowUpLeft"
      | "ArrowUpNarrowWide"
      | "ArrowUpRight"
      | "ArrowUpToLine"
      | "ArrowUpWideNarrow"
      | "ArrowUpZA"
      | "ArrowsUpFromLine"
      | "Asterisk"
      | "AtSign"
      | "Atom"
      | "AudioLines"
      | "AudioWaveform"
      | "Award"
      | "Axe"
      | "Axis3d"
      | "Baby"
      | "Backpack"
      | "Badge"
      | "BadgeAlert"
      | "BadgeCent"
      | "BadgeCheck"
      | "BadgeDollarSign"
      | "BadgeEuro"
      | "BadgeIndianRupee"
      | "BadgeInfo"
      | "BadgeJapaneseYen"
      | "BadgeMinus"
      | "BadgePercent"
      | "BadgePlus"
      | "BadgePoundSterling"
      | "BadgeQuestionMark"
      | "BadgeRussianRuble"
      | "BadgeSwissFranc"
      | "BadgeX"
      | "BaggageClaim"
      | "Ban"
      | "Banana"
      | "Bandage"
      | "Banknote"
      | "BanknoteArrowDown"
      | "BanknoteArrowUp"
      | "BanknoteX"
      | "Barcode"
      | "Barrel"
      | "Baseline"
      | "Bath"
      | "Battery"
      | "BatteryCharging"
      | "BatteryFull"
      | "BatteryLow"
      | "BatteryMedium"
      | "BatteryPlus"
      | "BatteryWarning"
      | "Beaker"
      | "Bean"
      | "BeanOff"
      | "Bed"
      | "BedDouble"
      | "BedSingle"
      | "Beef"
      | "Beer"
      | "BeerOff"
      | "Bell"
      | "BellDot"
      | "BellElectric"
      | "BellMinus"
      | "BellOff"
      | "BellPlus"
      | "BellRing"
      | "BetweenHorizontalEnd"
      | "BetweenHorizontalStart"
      | "BetweenVerticalEnd"
      | "BetweenVerticalStart"
      | "BicepsFlexed"
      | "Bike"
      | "Binary"
      | "Binoculars"
      | "Biohazard"
      | "Bird"
      | "Bitcoin"
      | "Blend"
      | "Blinds"
      | "Blocks"
      | "Bluetooth"
      | "BluetoothConnected"
      | "BluetoothOff"
      | "BluetoothSearching"
      | "Bold"
      | "Bolt"
      | "Bomb"
      | "Bone"
      | "Book"
      | "BookA"
      | "BookAlert"
      | "BookAudio"
      | "BookCheck"
      | "BookCopy"
      | "BookDashed"
      | "BookDown"
      | "BookHeadphones"
      | "BookHeart"
      | "BookImage"
      | "BookKey"
      | "BookLock"
      | "BookMarked"
      | "BookMinus"
      | "BookOpen"
      | "BookOpenCheck"
      | "BookOpenText"
      | "BookPlus"
      | "BookText"
      | "BookType"
      | "BookUp"
      | "BookUp2"
      | "BookUser"
      | "BookX"
      | "Bookmark"
      | "BookmarkCheck"
      | "BookmarkMinus"
      | "BookmarkPlus"
      | "BookmarkX"
      | "BoomBox"
      | "Bot"
      | "BotMessageSquare"
      | "BotOff"
      | "BottleWine"
      | "BowArrow"
      | "Box"
      | "Boxes"
      | "Braces"
      | "Brackets"
      | "Brain"
      | "BrainCircuit"
      | "BrainCog"
      | "BrickWall"
      | "BrickWallFire"
      | "Briefcase"
      | "BriefcaseBusiness"
      | "BriefcaseConveyorBelt"
      | "BriefcaseMedical"
      | "BringToFront"
      | "Brush"
      | "BrushCleaning"
      | "Bubbles"
      | "Bug"
      | "BugOff"
      | "BugPlay"
      | "Building"
      | "Building2"
      | "Bus"
      | "BusFront"
      | "Cable"
      | "CableCar"
      | "Cake"
      | "CakeSlice"
      | "Calculator"
      | "Calendar"
      | "Calendar1"
      | "CalendarArrowDown"
      | "CalendarArrowUp"
      | "CalendarCheck"
      | "CalendarCheck2"
      | "CalendarClock"
      | "CalendarCog"
      | "CalendarDays"
      | "CalendarFold"
      | "CalendarHeart"
      | "CalendarMinus"
      | "CalendarMinus2"
      | "CalendarOff"
      | "CalendarPlus"
      | "CalendarPlus2"
      | "CalendarRange"
      | "CalendarSearch"
      | "CalendarSync"
      | "CalendarX"
      | "CalendarX2"
      | "Camera"
      | "CameraOff"
      | "Candy"
      | "CandyCane"
      | "CandyOff"
      | "Cannabis"
      | "Captions"
      | "CaptionsOff"
      | "Car"
      | "CarFront"
      | "CarTaxiFront"
      | "Caravan"
      | "CardSim"
      | "Carrot"
      | "CaseLower"
      | "CaseSensitive"
      | "CaseUpper"
      | "CassetteTape"
      | "Cast"
      | "Castle"
      | "Cat"
      | "Cctv"
      | "ChartArea"
      | "ChartBar"
      | "ChartBarBig"
      | "ChartBarDecreasing"
      | "ChartBarIncreasing"
      | "ChartBarStacked"
      | "ChartCandlestick"
      | "ChartColumn"
      | "ChartColumnBig"
      | "ChartColumnDecreasing"
      | "ChartColumnIncreasing"
      | "ChartColumnStacked"
      | "ChartGantt"
      | "ChartLine"
      | "ChartNetwork"
      | "ChartNoAxesColumn"
      | "ChartNoAxesColumnDecreasing"
      | "ChartNoAxesColumnIncreasing"
      | "ChartNoAxesCombined"
      | "ChartNoAxesGantt"
      | "ChartPie"
      | "ChartScatter"
      | "ChartSpline"
      | "Check"
      | "CheckCheck"
      | "CheckLine"
      | "ChefHat"
      | "Cherry"
      | "ChevronDown"
      | "ChevronFirst"
      | "ChevronLast"
      | "ChevronLeft"
      | "ChevronRight"
      | "ChevronUp"
      | "ChevronsDown"
      | "ChevronsDownUp"
      | "ChevronsLeft"
      | "ChevronsLeftRight"
      | "ChevronsLeftRightEllipsis"
      | "ChevronsRight"
      | "ChevronsRightLeft"
      | "ChevronsUp"
      | "ChevronsUpDown"
      | "Chrome"
      | "Church"
      | "Cigarette"
      | "CigaretteOff"
      | "Circle"
      | "CircleAlert"
      | "CircleArrowDown"
      | "CircleArrowLeft"
      | "CircleArrowOutDownLeft"
      | "CircleArrowOutDownRight"
      | "CircleArrowOutUpLeft"
      | "CircleArrowOutUpRight"
      | "CircleArrowRight"
      | "CircleArrowUp"
      | "CircleCheck"
      | "CircleCheckBig"
      | "CircleChevronDown"
      | "CircleChevronLeft"
      | "CircleChevronRight"
      | "CircleChevronUp"
      | "CircleDashed"
      | "CircleDivide"
      | "CircleDollarSign"
      | "CircleDot"
      | "CircleDotDashed"
      | "CircleEllipsis"
      | "CircleEqual"
      | "CircleFadingArrowUp"
      | "CircleFadingPlus"
      | "CircleGauge"
      | "CircleMinus"
      | "CircleOff"
      | "CircleParking"
      | "CircleParkingOff"
      | "CirclePause"
      | "CirclePercent"
      | "CirclePlay"
      | "CirclePlus"
      | "CirclePoundSterling"
      | "CirclePower"
      | "CircleQuestionMark"
      | "CircleSlash"
      | "CircleSlash2"
      | "CircleSmall"
      | "CircleStop"
      | "CircleUser"
      | "CircleUserRound"
      | "CircleX"
      | "CircuitBoard"
      | "Citrus"
      | "Clapperboard"
      | "Clipboard"
      | "ClipboardCheck"
      | "ClipboardCopy"
      | "ClipboardList"
      | "ClipboardMinus"
      | "ClipboardPaste"
      | "ClipboardPen"
      | "ClipboardPenLine"
      | "ClipboardPlus"
      | "ClipboardType"
      | "ClipboardX"
      | "Clock"
      | "Clock1"
      | "Clock10"
      | "Clock11"
      | "Clock12"
      | "Clock2"
      | "Clock3"
      | "Clock4"
      | "Clock5"
      | "Clock6"
      | "Clock7"
      | "Clock8"
      | "Clock9"
      | "ClockAlert"
      | "ClockArrowDown"
      | "ClockArrowUp"
      | "ClockFading"
      | "ClockPlus"
      | "Cloud"
      | "CloudAlert"
      | "CloudCheck"
      | "CloudCog"
      | "CloudDownload"
      | "CloudDrizzle"
      | "CloudFog"
      | "CloudHail"
      | "CloudLightning"
      | "CloudMoon"
      | "CloudMoonRain"
      | "CloudOff"
      | "CloudRain"
      | "CloudRainWind"
      | "CloudSnow"
      | "CloudSun"
      | "CloudSunRain"
      | "CloudUpload"
      | "Cloudy"
      | "Clover"
      | "Club"
      | "Code"
      | "CodeXml"
      | "Codepen"
      | "Codesandbox"
      | "Coffee"
      | "Cog"
      | "Coins"
      | "Columns2"
      | "Columns3"
      | "Columns3Cog"
      | "Columns4"
      | "Combine"
      | "Command"
      | "Compass"
      | "Component"
      | "Computer"
      | "ConciergeBell"
      | "Cone"
      | "Construction"
      | "Contact"
      | "ContactRound"
      | "Container"
      | "Contrast"
      | "Cookie"
      | "CookingPot"
      | "Copy"
      | "CopyCheck"
      | "CopyMinus"
      | "CopyPlus"
      | "CopySlash"
      | "CopyX"
      | "Copyleft"
      | "Copyright"
      | "CornerDownLeft"
      | "CornerDownRight"
      | "CornerLeftDown"
      | "CornerLeftUp"
      | "CornerRightDown"
      | "CornerRightUp"
      | "CornerUpLeft"
      | "CornerUpRight"
      | "Cpu"
      | "CreativeCommons"
      | "CreditCard"
      | "Croissant"
      | "Crop"
      | "Cross"
      | "Crosshair"
      | "Crown"
      | "Cuboid"
      | "CupSoda"
      | "Currency"
      | "Cylinder"
      | "Dam"
      | "Database"
      | "DatabaseBackup"
      | "DatabaseZap"
      | "DecimalsArrowLeft"
      | "DecimalsArrowRight"
      | "Delete"
      | "Dessert"
      | "Diameter"
      | "Diamond"
      | "DiamondMinus"
      | "DiamondPercent"
      | "DiamondPlus"
      | "Dice1"
      | "Dice2"
      | "Dice3"
      | "Dice4"
      | "Dice5"
      | "Dice6"
      | "Dices"
      | "Diff"
      | "Disc"
      | "Disc2"
      | "Disc3"
      | "DiscAlbum"
      | "Divide"
      | "Dna"
      | "DnaOff"
      | "Dock"
      | "Dog"
      | "DollarSign"
      | "Donut"
      | "DoorClosed"
      | "DoorClosedLocked"
      | "DoorOpen"
      | "Dot"
      | "Download"
      | "DraftingCompass"
      | "Drama"
      | "Dribbble"
      | "Drill"
      | "Drone"
      | "Droplet"
      | "DropletOff"
      | "Droplets"
      | "Drum"
      | "Drumstick"
      | "Dumbbell"
      | "Ear"
      | "EarOff"
      | "Earth"
      | "EarthLock"
      | "Eclipse"
      | "Egg"
      | "EggFried"
      | "EggOff"
      | "Ellipsis"
      | "EllipsisVertical"
      | "Equal"
      | "EqualApproximately"
      | "EqualNot"
      | "Eraser"
      | "EthernetPort"
      | "Euro"
      | "Expand"
      | "ExternalLink"
      | "Eye"
      | "EyeClosed"
      | "EyeOff"
      | "Facebook"
      | "Factory"
      | "Fan"
      | "FastForward"
      | "Feather"
      | "Fence"
      | "FerrisWheel"
      | "Figma"
      | "File"
      | "FileArchive"
      | "FileAudio"
      | "FileAudio2"
      | "FileAxis3d"
      | "FileBadge"
      | "FileBadge2"
      | "FileBox"
      | "FileChartColumn"
      | "FileChartColumnIncreasing"
      | "FileChartLine"
      | "FileChartPie"
      | "FileCheck"
      | "FileCheck2"
      | "FileClock"
      | "FileCode"
      | "FileCode2"
      | "FileCog"
      | "FileDiff"
      | "FileDigit"
      | "FileDown"
      | "FileHeart"
      | "FileImage"
      | "FileInput"
      | "FileJson"
      | "FileJson2"
      | "FileKey"
      | "FileKey2"
      | "FileLock"
      | "FileLock2"
      | "FileMinus"
      | "FileMinus2"
      | "FileMusic"
      | "FileOutput"
      | "FilePen"
      | "FilePenLine"
      | "FilePlus"
      | "FilePlus2"
      | "FileQuestionMark"
      | "FileScan"
      | "FileSearch"
      | "FileSearch2"
      | "FileSliders"
      | "FileSpreadsheet"
      | "FileStack"
      | "FileSymlink"
      | "FileTerminal"
      | "FileText"
      | "FileType"
      | "FileType2"
      | "FileUp"
      | "FileUser"
      | "FileVideo"
      | "FileVideo2"
      | "FileVolume"
      | "FileVolume2"
      | "FileWarning"
      | "FileX"
      | "FileX2"
      | "Files"
      | "Film"
      | "Fingerprint"
      | "FireExtinguisher"
      | "Fish"
      | "FishOff"
      | "FishSymbol"
      | "Flag"
      | "FlagOff"
      | "FlagTriangleLeft"
      | "FlagTriangleRight"
      | "Flame"
      | "FlameKindling"
      | "Flashlight"
      | "FlashlightOff"
      | "FlaskConical"
      | "FlaskConicalOff"
      | "FlaskRound"
      | "FlipHorizontal"
      | "FlipHorizontal2"
      | "FlipVertical"
      | "FlipVertical2"
      | "Flower"
      | "Flower2"
      | "Focus"
      | "FoldHorizontal"
      | "FoldVertical"
      | "Folder"
      | "FolderArchive"
      | "FolderCheck"
      | "FolderClock"
      | "FolderClosed"
      | "FolderCode"
      | "FolderCog"
      | "FolderDot"
      | "FolderDown"
      | "FolderGit"
      | "FolderGit2"
      | "FolderHeart"
      | "FolderInput"
      | "FolderKanban"
      | "FolderKey"
      | "FolderLock"
      | "FolderMinus"
      | "FolderOpen"
      | "FolderOpenDot"
      | "FolderOutput"
      | "FolderPen"
      | "FolderPlus"
      | "FolderRoot"
      | "FolderSearch"
      | "FolderSearch2"
      | "FolderSymlink"
      | "FolderSync"
      | "FolderTree"
      | "FolderUp"
      | "FolderX"
      | "Folders"
      | "Footprints"
      | "Forklift"
      | "Forward"
      | "Frame"
      | "Framer"
      | "Frown"
      | "Fuel"
      | "Fullscreen"
      | "Funnel"
      | "FunnelPlus"
      | "FunnelX"
      | "GalleryHorizontal"
      | "GalleryHorizontalEnd"
      | "GalleryThumbnails"
      | "GalleryVertical"
      | "GalleryVerticalEnd"
      | "Gamepad"
      | "Gamepad2"
      | "Gauge"
      | "Gavel"
      | "Gem"
      | "GeorgianLari"
      | "Ghost"
      | "Gift"
      | "GitBranch"
      | "GitBranchPlus"
      | "GitCommitHorizontal"
      | "GitCommitVertical"
      | "GitCompare"
      | "GitCompareArrows"
      | "GitFork"
      | "GitGraph"
      | "GitMerge"
      | "GitPullRequest"
      | "GitPullRequestArrow"
      | "GitPullRequestClosed"
      | "GitPullRequestCreate"
      | "GitPullRequestCreateArrow"
      | "GitPullRequestDraft"
      | "Github"
      | "Gitlab"
      | "GlassWater"
      | "Glasses"
      | "Globe"
      | "GlobeLock"
      | "Goal"
      | "Gpu"
      | "Grab"
      | "GraduationCap"
      | "Grape"
      | "Grid2x2"
      | "Grid2x2Check"
      | "Grid2x2Plus"
      | "Grid2x2X"
      | "Grid3x2"
      | "Grid3x3"
      | "Grip"
      | "GripHorizontal"
      | "GripVertical"
      | "Group"
      | "Guitar"
      | "Ham"
      | "Hamburger"
      | "Hammer"
      | "Hand"
      | "HandCoins"
      | "HandHeart"
      | "HandHelping"
      | "HandMetal"
      | "HandPlatter"
      | "Handshake"
      | "HardDrive"
      | "HardDriveDownload"
      | "HardDriveUpload"
      | "HardHat"
      | "Hash"
      | "Haze"
      | "HdmiPort"
      | "Heading"
      | "Heading1"
      | "Heading2"
      | "Heading3"
      | "Heading4"
      | "Heading5"
      | "Heading6"
      | "HeadphoneOff"
      | "Headphones"
      | "Headset"
      | "Heart"
      | "HeartCrack"
      | "HeartHandshake"
      | "HeartMinus"
      | "HeartOff"
      | "HeartPlus"
      | "HeartPulse"
      | "Heater"
      | "Hexagon"
      | "Highlighter"
      | "History"
      | "Hop"
      | "HopOff"
      | "Hospital"
      | "Hotel"
      | "Hourglass"
      | "House"
      | "HousePlug"
      | "HousePlus"
      | "HouseWifi"
      | "IceCreamBowl"
      | "IceCreamCone"
      | "IdCard"
      | "IdCardLanyard"
      | "Image"
      | "ImageDown"
      | "ImageMinus"
      | "ImageOff"
      | "ImagePlay"
      | "ImagePlus"
      | "ImageUp"
      | "ImageUpscale"
      | "Images"
      | "Import"
      | "Inbox"
      | "IndentDecrease"
      | "IndentIncrease"
      | "IndianRupee"
      | "Infinity"
      | "Info"
      | "InspectionPanel"
      | "Instagram"
      | "Italic"
      | "IterationCcw"
      | "IterationCw"
      | "JapaneseYen"
      | "Joystick"
      | "Kanban"
      | "Key"
      | "KeyRound"
      | "KeySquare"
      | "Keyboard"
      | "KeyboardMusic"
      | "KeyboardOff"
      | "Lamp"
      | "LampCeiling"
      | "LampDesk"
      | "LampFloor"
      | "LampWallDown"
      | "LampWallUp"
      | "LandPlot"
      | "Landmark"
      | "Languages"
      | "Laptop"
      | "LaptopMinimal"
      | "LaptopMinimalCheck"
      | "Lasso"
      | "LassoSelect"
      | "Laugh"
      | "Layers"
      | "Layers2"
      | "LayoutDashboard"
      | "LayoutGrid"
      | "LayoutList"
      | "LayoutPanelLeft"
      | "LayoutPanelTop"
      | "LayoutTemplate"
      | "Leaf"
      | "LeafyGreen"
      | "Lectern"
      | "LetterText"
      | "Library"
      | "LibraryBig"
      | "LifeBuoy"
      | "Ligature"
      | "Lightbulb"
      | "LightbulbOff"
      | "LineSquiggle"
      | "Link"
      | "Link2"
      | "Link2Off"
      | "Linkedin"
      | "List"
      | "ListCheck"
      | "ListChecks"
      | "ListCollapse"
      | "ListEnd"
      | "ListFilter"
      | "ListFilterPlus"
      | "ListMinus"
      | "ListMusic"
      | "ListOrdered"
      | "ListPlus"
      | "ListRestart"
      | "ListStart"
      | "ListTodo"
      | "ListTree"
      | "ListVideo"
      | "ListX"
      | "Loader"
      | "LoaderCircle"
      | "LoaderPinwheel"
      | "Locate"
      | "LocateFixed"
      | "LocateOff"
      | "LocationEdit"
      | "Lock"
      | "LockKeyhole"
      | "LockKeyholeOpen"
      | "LockOpen"
      | "LogIn"
      | "LogOut"
      | "Logs"
      | "Lollipop"
      | "Luggage"
      | "Magnet"
      | "Mail"
      | "MailCheck"
      | "MailMinus"
      | "MailOpen"
      | "MailPlus"
      | "MailQuestionMark"
      | "MailSearch"
      | "MailWarning"
      | "MailX"
      | "Mailbox"
      | "Mails"
      | "Map"
      | "MapPin"
      | "MapPinCheck"
      | "MapPinCheckInside"
      | "MapPinHouse"
      | "MapPinMinus"
      | "MapPinMinusInside"
      | "MapPinOff"
      | "MapPinPlus"
      | "MapPinPlusInside"
      | "MapPinX"
      | "MapPinXInside"
      | "MapPinned"
      | "MapPlus"
      | "Mars"
      | "MarsStroke"
      | "Martini"
      | "Maximize"
      | "Maximize2"
      | "Medal"
      | "Megaphone"
      | "MegaphoneOff"
      | "Meh"
      | "MemoryStick"
      | "Menu"
      | "Merge"
      | "MessageCircle"
      | "MessageCircleCode"
      | "MessageCircleDashed"
      | "MessageCircleHeart"
      | "MessageCircleMore"
      | "MessageCircleOff"
      | "MessageCirclePlus"
      | "MessageCircleQuestionMark"
      | "MessageCircleReply"
      | "MessageCircleWarning"
      | "MessageCircleX"
      | "MessageSquare"
      | "MessageSquareCode"
      | "MessageSquareDashed"
      | "MessageSquareDiff"
      | "MessageSquareDot"
      | "MessageSquareHeart"
      | "MessageSquareLock"
      | "MessageSquareMore"
      | "MessageSquareOff"
      | "MessageSquarePlus"
      | "MessageSquareQuote"
      | "MessageSquareReply"
      | "MessageSquareShare"
      | "MessageSquareText"
      | "MessageSquareWarning"
      | "MessageSquareX"
      | "MessagesSquare"
      | "Mic"
      | "MicOff"
      | "MicVocal"
      | "Microchip"
      | "Microscope"
      | "Microwave"
      | "Milestone"
      | "Milk"
      | "MilkOff"
      | "Minimize"
      | "Minimize2"
      | "Minus"
      | "Monitor"
      | "MonitorCheck"
      | "MonitorCog"
      | "MonitorDot"
      | "MonitorDown"
      | "MonitorOff"
      | "MonitorPause"
      | "MonitorPlay"
      | "MonitorSmartphone"
      | "MonitorSpeaker"
      | "MonitorStop"
      | "MonitorUp"
      | "MonitorX"
      | "Moon"
      | "MoonStar"
      | "Mountain"
      | "MountainSnow"
      | "Mouse"
      | "MouseOff"
      | "MousePointer"
      | "MousePointer2"
      | "MousePointerBan"
      | "MousePointerClick"
      | "Move"
      | "Move3d"
      | "MoveDiagonal"
      | "MoveDiagonal2"
      | "MoveDown"
      | "MoveDownLeft"
      | "MoveDownRight"
      | "MoveHorizontal"
      | "MoveLeft"
      | "MoveRight"
      | "MoveUp"
      | "MoveUpLeft"
      | "MoveUpRight"
      | "MoveVertical"
      | "Music"
      | "Music2"
      | "Music3"
      | "Music4"
      | "Navigation"
      | "Navigation2"
      | "Navigation2Off"
      | "NavigationOff"
      | "Network"
      | "Newspaper"
      | "Nfc"
      | "NonBinary"
      | "Notebook"
      | "NotebookPen"
      | "NotebookTabs"
      | "NotebookText"
      | "NotepadText"
      | "NotepadTextDashed"
      | "Nut"
      | "NutOff"
      | "Octagon"
      | "OctagonAlert"
      | "OctagonMinus"
      | "OctagonPause"
      | "OctagonX"
      | "Omega"
      | "Option"
      | "Orbit"
      | "Origami"
      | "Package"
      | "Package2"
      | "PackageCheck"
      | "PackageMinus"
      | "PackageOpen"
      | "PackagePlus"
      | "PackageSearch"
      | "PackageX"
      | "PaintBucket"
      | "PaintRoller"
      | "Paintbrush"
      | "PaintbrushVertical"
      | "Palette"
      | "Panda"
      | "PanelBottom"
      | "PanelBottomClose"
      | "PanelBottomDashed"
      | "PanelBottomOpen"
      | "PanelLeft"
      | "PanelLeftClose"
      | "PanelLeftDashed"
      | "PanelLeftOpen"
      | "PanelRight"
      | "PanelRightClose"
      | "PanelRightDashed"
      | "PanelRightOpen"
      | "PanelTop"
      | "PanelTopClose"
      | "PanelTopDashed"
      | "PanelTopOpen"
      | "PanelsLeftBottom"
      | "PanelsRightBottom"
      | "PanelsTopLeft"
      | "Paperclip"
      | "Parentheses"
      | "ParkingMeter"
      | "PartyPopper"
      | "Pause"
      | "PawPrint"
      | "PcCase"
      | "Pen"
      | "PenLine"
      | "PenOff"
      | "PenTool"
      | "Pencil"
      | "PencilLine"
      | "PencilOff"
      | "PencilRuler"
      | "Pentagon"
      | "Percent"
      | "PersonStanding"
      | "PhilippinePeso"
      | "Phone"
      | "PhoneCall"
      | "PhoneForwarded"
      | "PhoneIncoming"
      | "PhoneMissed"
      | "PhoneOff"
      | "PhoneOutgoing"
      | "Pi"
      | "Piano"
      | "Pickaxe"
      | "PictureInPicture"
      | "PictureInPicture2"
      | "PiggyBank"
      | "Pilcrow"
      | "PilcrowLeft"
      | "PilcrowRight"
      | "Pill"
      | "PillBottle"
      | "Pin"
      | "PinOff"
      | "Pipette"
      | "Pizza"
      | "Plane"
      | "PlaneLanding"
      | "PlaneTakeoff"
      | "Play"
      | "Plug"
      | "Plug2"
      | "PlugZap"
      | "Plus"
      | "Pocket"
      | "PocketKnife"
      | "Podcast"
      | "Pointer"
      | "PointerOff"
      | "Popcorn"
      | "Popsicle"
      | "PoundSterling"
      | "Power"
      | "PowerOff"
      | "Presentation"
      | "Printer"
      | "PrinterCheck"
      | "Projector"
      | "Proportions"
      | "Puzzle"
      | "Pyramid"
      | "QrCode"
      | "Quote"
      | "Rabbit"
      | "Radar"
      | "Radiation"
      | "Radical"
      | "Radio"
      | "RadioReceiver"
      | "RadioTower"
      | "Radius"
      | "RailSymbol"
      | "Rainbow"
      | "Rat"
      | "Ratio"
      | "Receipt"
      | "ReceiptCent"
      | "ReceiptEuro"
      | "ReceiptIndianRupee"
      | "ReceiptJapaneseYen"
      | "ReceiptPoundSterling"
      | "ReceiptRussianRuble"
      | "ReceiptSwissFranc"
      | "ReceiptText"
      | "RectangleCircle"
      | "RectangleEllipsis"
      | "RectangleGoggles"
      | "RectangleHorizontal"
      | "RectangleVertical"
      | "Recycle"
      | "Redo"
      | "Redo2"
      | "RedoDot"
      | "RefreshCcw"
      | "RefreshCcwDot"
      | "RefreshCw"
      | "RefreshCwOff"
      | "Refrigerator"
      | "Regex"
      | "RemoveFormatting"
      | "Repeat"
      | "Repeat1"
      | "Repeat2"
      | "Replace"
      | "ReplaceAll"
      | "Reply"
      | "ReplyAll"
      | "Rewind"
      | "Ribbon"
      | "Rocket"
      | "RockingChair"
      | "RollerCoaster"
      | "Rotate3d"
      | "RotateCcw"
      | "RotateCcwKey"
      | "RotateCcwSquare"
      | "RotateCw"
      | "RotateCwSquare"
      | "Route"
      | "RouteOff"
      | "Router"
      | "Rows2"
      | "Rows3"
      | "Rows4"
      | "Rss"
      | "Ruler"
      | "RulerDimensionLine"
      | "RussianRuble"
      | "Sailboat"
      | "Salad"
      | "Sandwich"
      | "Satellite"
      | "SatelliteDish"
      | "SaudiRiyal"
      | "Save"
      | "SaveAll"
      | "SaveOff"
      | "Scale"
      | "Scale3d"
      | "Scaling"
      | "Scan"
      | "ScanBarcode"
      | "ScanEye"
      | "ScanFace"
      | "ScanHeart"
      | "ScanLine"
      | "ScanQrCode"
      | "ScanSearch"
      | "ScanText"
      | "School"
      | "Scissors"
      | "ScissorsLineDashed"
      | "ScreenShare"
      | "ScreenShareOff"
      | "Scroll"
      | "ScrollText"
      | "Search"
      | "SearchCheck"
      | "SearchCode"
      | "SearchSlash"
      | "SearchX"
      | "Section"
      | "Send"
      | "SendHorizontal"
      | "SendToBack"
      | "SeparatorHorizontal"
      | "SeparatorVertical"
      | "Server"
      | "ServerCog"
      | "ServerCrash"
      | "ServerOff"
      | "Settings"
      | "Settings2"
      | "Shapes"
      | "Share"
      | "Share2"
      | "Sheet"
      | "Shell"
      | "Shield"
      | "ShieldAlert"
      | "ShieldBan"
      | "ShieldCheck"
      | "ShieldEllipsis"
      | "ShieldHalf"
      | "ShieldMinus"
      | "ShieldOff"
      | "ShieldPlus"
      | "ShieldQuestionMark"
      | "ShieldUser"
      | "ShieldX"
      | "Ship"
      | "ShipWheel"
      | "Shirt"
      | "ShoppingBag"
      | "ShoppingBasket"
      | "ShoppingCart"
      | "Shovel"
      | "ShowerHead"
      | "Shredder"
      | "Shrimp"
      | "Shrink"
      | "Shrub"
      | "Shuffle"
      | "Sigma"
      | "Signal"
      | "SignalHigh"
      | "SignalLow"
      | "SignalMedium"
      | "SignalZero"
      | "Signature"
      | "Signpost"
      | "SignpostBig"
      | "Siren"
      | "SkipBack"
      | "SkipForward"
      | "Skull"
      | "Slack"
      | "Slash"
      | "Slice"
      | "SlidersHorizontal"
      | "SlidersVertical"
      | "Smartphone"
      | "SmartphoneCharging"
      | "SmartphoneNfc"
      | "Smile"
      | "SmilePlus"
      | "Snail"
      | "Snowflake"
      | "SoapDispenserDroplet"
      | "Sofa"
      | "Soup"
      | "Space"
      | "Spade"
      | "Sparkle"
      | "Sparkles"
      | "Speaker"
      | "Speech"
      | "SpellCheck"
      | "SpellCheck2"
      | "Spline"
      | "SplinePointer"
      | "Split"
      | "Spool"
      | "SprayCan"
      | "Sprout"
      | "Square"
      | "SquareActivity"
      | "SquareArrowDown"
      | "SquareArrowDownLeft"
      | "SquareArrowDownRight"
      | "SquareArrowLeft"
      | "SquareArrowOutDownLeft"
      | "SquareArrowOutDownRight"
      | "SquareArrowOutUpLeft"
      | "SquareArrowOutUpRight"
      | "SquareArrowRight"
      | "SquareArrowUp"
      | "SquareArrowUpLeft"
      | "SquareArrowUpRight"
      | "SquareAsterisk"
      | "SquareBottomDashedScissors"
      | "SquareChartGantt"
      | "SquareCheck"
      | "SquareCheckBig"
      | "SquareChevronDown"
      | "SquareChevronLeft"
      | "SquareChevronRight"
      | "SquareChevronUp"
      | "SquareCode"
      | "SquareDashed"
      | "SquareDashedBottom"
      | "SquareDashedBottomCode"
      | "SquareDashedKanban"
      | "SquareDashedMousePointer"
      | "SquareDashedTopSolid"
      | "SquareDivide"
      | "SquareDot"
      | "SquareEqual"
      | "SquareFunction"
      | "SquareKanban"
      | "SquareLibrary"
      | "SquareM"
      | "SquareMenu"
      | "SquareMinus"
      | "SquareMousePointer"
      | "SquareParking"
      | "SquareParkingOff"
      | "SquarePen"
      | "SquarePercent"
      | "SquarePi"
      | "SquarePilcrow"
      | "SquarePlay"
      | "SquarePlus"
      | "SquarePower"
      | "SquareRadical"
      | "SquareRoundCorner"
      | "SquareScissors"
      | "SquareSigma"
      | "SquareSlash"
      | "SquareSplitHorizontal"
      | "SquareSplitVertical"
      | "SquareSquare"
      | "SquareStack"
      | "SquareTerminal"
      | "SquareUser"
      | "SquareUserRound"
      | "SquareX"
      | "SquaresExclude"
      | "SquaresIntersect"
      | "SquaresSubtract"
      | "SquaresUnite"
      | "Squircle"
      | "SquircleDashed"
      | "Squirrel"
      | "Stamp"
      | "Star"
      | "StarHalf"
      | "StarOff"
      | "StepBack"
      | "StepForward"
      | "Stethoscope"
      | "Sticker"
      | "StickyNote"
      | "Store"
      | "StretchHorizontal"
      | "StretchVertical"
      | "Strikethrough"
      | "Subscript"
      | "Sun"
      | "SunDim"
      | "SunMedium"
      | "SunMoon"
      | "SunSnow"
      | "Sunrise"
      | "Sunset"
      | "Superscript"
      | "SwatchBook"
      | "SwissFranc"
      | "SwitchCamera"
      | "Sword"
      | "Swords"
      | "Syringe"
      | "Table"
      | "Table2"
      | "TableCellsMerge"
      | "TableCellsSplit"
      | "TableColumnsSplit"
      | "TableOfContents"
      | "TableProperties"
      | "TableRowsSplit"
      | "Tablet"
      | "TabletSmartphone"
      | "Tablets"
      | "Tag"
      | "Tags"
      | "Tally1"
      | "Tally2"
      | "Tally3"
      | "Tally4"
      | "Tally5"
      | "Tangent"
      | "Target"
      | "Telescope"
      | "Tent"
      | "TentTree"
      | "Terminal"
      | "TestTube"
      | "TestTubeDiagonal"
      | "TestTubes"
      | "Text"
      | "TextCursor"
      | "TextCursorInput"
      | "TextQuote"
      | "TextSearch"
      | "TextSelect"
      | "Theater"
      | "Thermometer"
      | "ThermometerSnowflake"
      | "ThermometerSun"
      | "ThumbsDown"
      | "ThumbsUp"
      | "Ticket"
      | "TicketCheck"
      | "TicketMinus"
      | "TicketPercent"
      | "TicketPlus"
      | "TicketSlash"
      | "TicketX"
      | "Tickets"
      | "TicketsPlane"
      | "Timer"
      | "TimerOff"
      | "TimerReset"
      | "ToggleLeft"
      | "ToggleRight"
      | "Toilet"
      | "ToolCase"
      | "Tornado"
      | "Torus"
      | "Touchpad"
      | "TouchpadOff"
      | "TowerControl"
      | "ToyBrick"
      | "Tractor"
      | "TrafficCone"
      | "TrainFront"
      | "TrainFrontTunnel"
      | "TrainTrack"
      | "TramFront"
      | "Transgender"
      | "Trash"
      | "Trash2"
      | "TreeDeciduous"
      | "TreePalm"
      | "TreePine"
      | "Trees"
      | "Trello"
      | "TrendingDown"
      | "TrendingUp"
      | "TrendingUpDown"
      | "Triangle"
      | "TriangleAlert"
      | "TriangleDashed"
      | "TriangleRight"
      | "Trophy"
      | "Truck"
      | "TruckElectric"
      | "Turtle"
      | "Tv"
      | "TvMinimal"
      | "TvMinimalPlay"
      | "Twitch"
      | "Twitter"
      | "Type"
      | "TypeOutline"
      | "Umbrella"
      | "UmbrellaOff"
      | "Underline"
      | "Undo"
      | "Undo2"
      | "UndoDot"
      | "UnfoldHorizontal"
      | "UnfoldVertical"
      | "Ungroup"
      | "University"
      | "Unlink"
      | "Unlink2"
      | "Unplug"
      | "Upload"
      | "Usb"
      | "User"
      | "UserCheck"
      | "UserCog"
      | "UserLock"
      | "UserMinus"
      | "UserPen"
      | "UserPlus"
      | "UserRound"
      | "UserRoundCheck"
      | "UserRoundCog"
      | "UserRoundMinus"
      | "UserRoundPen"
      | "UserRoundPlus"
      | "UserRoundSearch"
      | "UserRoundX"
      | "UserSearch"
      | "UserX"
      | "Users"
      | "UsersRound"
      | "Utensils"
      | "UtensilsCrossed"
      | "UtilityPole"
      | "Variable"
      | "Vault"
      | "VectorSquare"
      | "Vegan"
      | "VenetianMask"
      | "Venus"
      | "VenusAndMars"
      | "Vibrate"
      | "VibrateOff"
      | "Video"
      | "VideoOff"
      | "Videotape"
      | "View"
      | "Voicemail"
      | "Volleyball"
      | "Volume"
      | "Volume1"
      | "Volume2"
      | "VolumeOff"
      | "VolumeX"
      | "Vote"
      | "Wallet"
      | "WalletCards"
      | "WalletMinimal"
      | "Wallpaper"
      | "Wand"
      | "WandSparkles"
      | "Warehouse"
      | "WashingMachine"
      | "Watch"
      | "Waves"
      | "WavesLadder"
      | "Waypoints"
      | "Webcam"
      | "Webhook"
      | "WebhookOff"
      | "Weight"
      | "Wheat"
      | "WheatOff"
      | "WholeWord"
      | "Wifi"
      | "WifiCog"
      | "WifiHigh"
      | "WifiLow"
      | "WifiOff"
      | "WifiPen"
      | "WifiZero"
      | "Wind"
      | "WindArrowDown"
      | "Wine"
      | "WineOff"
      | "Workflow"
      | "Worm"
      | "WrapText"
      | "Wrench"
      | "X"
      | "Youtube"
      | "Zap"
      | "ZapOff"
      | "ZoomIn"
      | "ZoomOut"
    )
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    sessions: Session;
    accounts: Account;
    verifications: Verification;
    pages: Page;
    media: Media;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    verifications: VerificationsSelect<false> | VerificationsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
    tailwind: Tailwind;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    tailwind: TailwindSelect<false> | TailwindSelect<true>;
  };
  locale: null;
  user: User & {
    collection: "users";
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  email: string;
  emailVerified: boolean;
  name: string;
  image?: string | null;
  role: "admin" | "user";
  banned: boolean;
  banReason?: string | null;
  banExpiresIn?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: string;
  userId: string | User;
  token: string;
  expiresAt: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: string;
  userId: string | User;
  accountId: string;
  providerId: string;
  accessToken?: string | null;
  refreshToken?: string | null;
  accessTokenExpiresAt?: string | null;
  refreshTokenExpiresAt?: string | null;
  scope?: string | null;
  idToken?: string | null;
  password?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications".
 */
export interface Verification {
  id: string;
  identifier: string;
  value: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  slug: string;
  title: string;
  showHeader: boolean;
  showFooter: boolean;
  blocks: (Teams_1_Block | Features_1_Block | Hero_1_Block)[];
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Teams_1_Block".
 */
export interface Teams_1_Block {
  blocks: (Teams_1_Heading_Block | Teams_1_Members_Block)[];
  id?: string | null;
  blockName?: string | null;
  blockType: "teams_1";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Teams_1_Heading_Block".
 */
export interface Teams_1_Heading_Block {
  text: string;
  id?: string | null;
  blockName?: string | null;
  blockType: "teams_1_heading";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Teams_1_Members_Block".
 */
export interface Teams_1_Members_Block {
  members: {
    name: string;
    role: string;
    avatar?: (string | null) | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: "teams_1_members";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Features_1_Block".
 */
export interface Features_1_Block {
  header: string;
  subheader: string;
  features: {
    title: string;
    description: string;
    icon?: IconField;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: "features_1";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero_1_Block".
 */
export interface Hero_1_Block {
  alertLabel?: string | null;
  alertLink?: string | null;
  header: string;
  subheader?: string | null;
  primaryCtaLabel: string;
  primaryCtaHref: string;
  secondaryCtaLabel: string;
  secondaryCtaHref: string;
  media?: {
    light?: (string | null) | Media;
    dark?: (string | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "hero_1";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: "users";
        value: string | User;
      } | null)
    | ({
        relationTo: "sessions";
        value: string | Session;
      } | null)
    | ({
        relationTo: "accounts";
        value: string | Account;
      } | null)
    | ({
        relationTo: "verifications";
        value: string | Verification;
      } | null)
    | ({
        relationTo: "pages";
        value: string | Page;
      } | null)
    | ({
        relationTo: "media";
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  email?: T;
  emailVerified?: T;
  name?: T;
  image?: T;
  role?: T;
  banned?: T;
  banReason?: T;
  banExpiresIn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  userId?: T;
  token?: T;
  expiresAt?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  userId?: T;
  accountId?: T;
  providerId?: T;
  accessToken?: T;
  refreshToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  idToken?: T;
  password?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications_select".
 */
export interface VerificationsSelect<T extends boolean = true> {
  identifier?: T;
  value?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  showHeader?: T;
  showFooter?: T;
  blocks?:
    | T
    | {
        teams_1?: T | Teams_1_BlockSelect<T>;
        features_1?: T | Features_1_BlockSelect<T>;
        hero_1?: T | Hero_1_BlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Teams_1_Block_select".
 */
export interface Teams_1_BlockSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        teams_1_heading?: T | Teams_1_Heading_BlockSelect<T>;
        teams_1_members?: T | Teams_1_Members_BlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Teams_1_Heading_Block_select".
 */
export interface Teams_1_Heading_BlockSelect<T extends boolean = true> {
  text?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Teams_1_Members_Block_select".
 */
export interface Teams_1_Members_BlockSelect<T extends boolean = true> {
  members?:
    | T
    | {
        name?: T;
        role?: T;
        avatar?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Features_1_Block_select".
 */
export interface Features_1_BlockSelect<T extends boolean = true> {
  header?: T;
  subheader?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero_1_Block_select".
 */
export interface Hero_1_BlockSelect<T extends boolean = true> {
  alertLabel?: T;
  alertLink?: T;
  header?: T;
  subheader?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  media?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  header: (Header_1_Block | Header_2_Block)[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Header_1_Block".
 */
export interface Header_1_Block {
  menuItems: {
    label: string;
    href: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: "header_1";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Header_2_Block".
 */
export interface Header_2_Block {
  menuItems: {
    label: string;
    href: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: "header_2";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  footer: Footer_1_Block[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Footer_1_Block".
 */
export interface Footer_1_Block {
  brandLogo?: (string | null) | Media;
  copyright?: string | null;
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks: {
    href: string;
    icon:
      | "Facebook"
      | "Twitter"
      | "YouTube"
      | "LinkedIn"
      | "Telegram"
      | "Matrix"
      | "WhatsApp"
      | "Arc"
      | "Mastodon"
      | "Messenger"
      | "Infojobs"
      | "Skype"
      | "Threads"
      | "Instagram"
      | "X (formerly Twitter)"
      | "VK"
      | "Hashnode"
      | "Patreon"
      | "Peerlist"
      | "Pinterest"
      | "Reddit"
      | "Meta"
      | "TikTok"
      | "Carrd"
      | "Bluesky"
      | "daily.dev";
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: "footer_1";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tailwind".
 */
export interface Tailwind {
  id: string;
  radius?: number | null;
  background?: string | null;
  foreground?: string | null;
  card?: string | null;
  "card-foreground"?: string | null;
  popover?: string | null;
  "popover-foreground"?: string | null;
  primary?: string | null;
  "primary-foreground"?: string | null;
  secondary?: string | null;
  "secondary-foreground"?: string | null;
  muted?: string | null;
  "muted-foreground"?: string | null;
  accent?: string | null;
  "accent-foreground"?: string | null;
  destructive?: string | null;
  "destructive-foreground"?: string | null;
  border?: string | null;
  input?: string | null;
  ring?: string | null;
  "chart-1"?: string | null;
  "chart-2"?: string | null;
  "chart-3"?: string | null;
  "chart-4"?: string | null;
  "chart-5"?: string | null;
  sidebar?: string | null;
  "sidebar-foreground"?: string | null;
  "sidebar-primary"?: string | null;
  "sidebar-primary-foreground"?: string | null;
  "sidebar-accent"?: string | null;
  "sidebar-accent-foreground"?: string | null;
  "sidebar-border"?: string | null;
  "sidebar-ring"?: string | null;
  _status?: ("draft" | "published") | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  header?:
    | T
    | {
        header_1?: T | Header_1_BlockSelect<T>;
        header_2?: T | Header_2_BlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Header_1_Block_select".
 */
export interface Header_1_BlockSelect<T extends boolean = true> {
  menuItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Header_2_Block_select".
 */
export interface Header_2_BlockSelect<T extends boolean = true> {
  menuItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  footer?:
    | T
    | {
        footer_1?: T | Footer_1_BlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Footer_1_Block_select".
 */
export interface Footer_1_BlockSelect<T extends boolean = true> {
  brandLogo?: T;
  copyright?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        href?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tailwind_select".
 */
export interface TailwindSelect<T extends boolean = true> {
  radius?: T;
  background?: T;
  foreground?: T;
  card?: T;
  "card-foreground"?: T;
  popover?: T;
  "popover-foreground"?: T;
  primary?: T;
  "primary-foreground"?: T;
  secondary?: T;
  "secondary-foreground"?: T;
  muted?: T;
  "muted-foreground"?: T;
  accent?: T;
  "accent-foreground"?: T;
  destructive?: T;
  "destructive-foreground"?: T;
  border?: T;
  input?: T;
  ring?: T;
  "chart-1"?: T;
  "chart-2"?: T;
  "chart-3"?: T;
  "chart-4"?: T;
  "chart-5"?: T;
  sidebar?: T;
  "sidebar-foreground"?: T;
  "sidebar-primary"?: T;
  "sidebar-primary-foreground"?: T;
  "sidebar-accent"?: T;
  "sidebar-accent-foreground"?: T;
  "sidebar-border"?: T;
  "sidebar-ring"?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
