name: Manual Playwright Test

on:
  workflow_dispatch:
    inputs:
      deployment_url:
        description: "Deployment URL to test"
        required: true
        default: "https://dev.uifoundry.dev"
        type: string
      browser:
        description: "Browser to test"
        required: false
        default: "chromium"
        type: choice
        options:
          - chromium
          - firefox
          - webkit
          - all

jobs:
  manual-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: |
          if [ "${{ github.event.inputs.browser }}" == "all" ]; then
            pnpm exec playwright install --with-deps
          else
            pnpm exec playwright install --with-deps ${{ github.event.inputs.browser }}
          fi

      - name: Run Playwright tests
        env:
          NEXT_PUBLIC_BETTER_AUTH_URL: ${{ github.event.inputs.deployment_url }}
        run: |
          if [ "${{ github.event.inputs.browser }}" == "all" ]; then
            pnpm exec playwright test
          else
            pnpm exec playwright test --project=${{ github.event.inputs.browser }}
          fi

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: manual-test-report-${{ github.run_id }}
          path: playwright-report/
          retention-days: 7

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: manual-test-results-${{ github.run_id }}
          path: test-results/
          retention-days: 7
